#!/usr/bin/env python3
"""Compile manifest-declared locale JSON files into a local JavaScript bundle."""

import argparse
import json
from pathlib import Path
import sys


HEADER = "// Generated by scripts/compile_locales.py from manifest locales.\n"


def json_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def reject_constant(value):
    raise ValueError(f"invalid JSON number: {value}")


def load_json(path: Path, label: str):
    try:
        return json.loads(
            path.read_text(encoding="utf-8"),
            object_pairs_hook=json_object,
            parse_constant=reject_constant,
        )
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ValueError(f"{label}: {error}") from error


def compile_locales(template_dir: Path) -> str:
    template_dir = template_dir.resolve()
    manifest_path = template_dir / "manifest.json"
    manifest = load_json(manifest_path, "manifest.json")
    if not isinstance(manifest, dict):
        raise ValueError("manifest.json must contain an object")
    locales = manifest.get("locales")
    default_locale = manifest.get("defaultLocale")
    if not isinstance(locales, dict) or not locales:
        raise ValueError("manifest.locales must be a nonempty object")
    if default_locale not in locales:
        raise ValueError("manifest.locales must include defaultLocale")

    messages = {}
    expected_keys = None
    for locale, relative in locales.items():
        if not isinstance(locale, str) or not locale:
            raise ValueError("locale names must be nonempty strings")
        if not isinstance(relative, str) or not relative:
            raise ValueError(f"manifest.locales.{locale} must be a path")
        if (
            Path(relative).is_absolute()
            or any(character in relative for character in "\\:?#")
            or any(part in ("", ".", "..") for part in relative.split("/"))
        ):
            raise ValueError(f"manifest.locales.{locale} must be a normalized package path")
        path = (template_dir / relative).resolve()
        if template_dir not in path.parents:
            raise ValueError(f"manifest.locales.{locale} escapes the template directory")
        value = load_json(path, relative)
        if not isinstance(value, dict) or any(
            not isinstance(key, str) or not isinstance(text, str)
            for key, text in value.items()
        ):
            raise ValueError(f"{relative} must contain a string-to-string object")
        keys = set(value)
        if expected_keys is None:
            expected_keys = keys
        elif keys != expected_keys:
            missing = sorted(expected_keys - keys)
            extra = sorted(keys - expected_keys)
            raise ValueError(
                f"{relative} keys differ; missing={missing}, extra={extra}"
            )
        messages[locale] = value

    encoded = json.dumps(
        messages,
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
        separators=(",", ": "),
    )
    return f"{HEADER}window.MINIPAGE_MESSAGES = {encoded};\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("template_dir", type=Path)
    parser.add_argument("--output", default="i18n.js")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = args.template_dir / args.output
    try:
        generated = compile_locales(args.template_dir)
        if args.check:
            if not target.is_file() or target.read_text(encoding="utf-8") != generated:
                raise ValueError(f"{args.output} is stale; run compile_locales.py")
            print(f"Locale bundle is current: {target}")
        else:
            target.write_text(generated, encoding="utf-8")
            print(f"Wrote {target}")
    except (ValueError, OSError) as error:
        print(f"Locale compilation failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
